name: auto-formatting action hero

on:
  push:
    branches:
      - master
      - devel
  # workflow_dispatch allows the action to be run manually
  workflow_dispatch:

jobs:
  autoformat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run PHP-CS-Fixer
        # See https://hub.docker.com/r/oskarstark/php-cs-fixer-ga
        uses: docker://oskarstark/php-cs-fixer-ga:3.7.0
        with:
          args: --config=.php-cs-fixer.php --diff

      - name: Install prettier
        run: npm install --global prettier@2.6.2

      - name: Run prettier
        # Uses config file .prettierrc
        run: prettier --loglevel debug --write .

      - name: Install black
        run: pip install black==22.3.0

      - name: Run black
        run: black . -v

      # See https://github.com/marketplace/actions/git-auto-commit
      - id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Autoformatted by Autoformatting Action Hero"
          commit_user_name: "Autoformatting Action Hero"

      - name: Give cookie
        if: steps.auto_commit.outputs.changes_detected == 'false'
        run: |
          echo << "EOF"
                       U _____ u  _       _           ____      U  ___ u  _   _   U _____ u
           __        __\| ___"|/ |"|     |"|         |  _"\      \/"_ \/ | \ |"|  \| ___"|/
           \"\      /"/ |  _|" U | | u U | | u      /| | | |     | | | |<|  \| |>  |  _|"
           /\ \ /\ / /\ | |___  \| |/__ \| |/__     U| |_| |\.-,_| |_| |U| |\  |u  | |___
          U  \ V  V /  U|_____|  |_____| |_____|     |____/ u \_)-\___/  |_| \_|   |_____|
          .-,_\ /\ /_,-.<<   >>  //  \\  //  \\       |||_         \\    ||   \\,-.<<   >>
           \_)-'  '-(_/(__) (__)(_")("_)(_")("_)     (__)_)       (__)   (_")  (_/(__) (__)
          EOF

      - name: Chastise
        if: steps.auto_commit.outputs.changes_detected == 'true'
        run: |
          echo << "EOF"
           ___     _       _       _
          |_ _|___| |__  _| |_ ___| |__
           | |<_-<| / /   | | <_-<| / /
           |_|/__/|_\_\   |_| /__/|_\_\
          EOF
