name: PHP-CS-Fixer
on: [push]
jobs:
  Obtain-modified-files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    steps:
      - name: checkout branch with history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get changed files
        id: changes
        run: echo "::set-output name=changed::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }}..${{ github.event.after }} | xargs)"
  Print-files:
    runs-on: ubuntu-latest
    needs: Obtain-modified-files
    if: ${{ needs.Obtain-modified-files.outputs.changed }}
    steps:
      - name: echo changed files
        run: echo ${{ needs.Obtain-modified-files.outputs.changed }}
      - name: Php-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --diff --dry-run
