name: auto-formatting action hero
on:
  push:
    branches:
      - master
      - devel
  # want to trigger workflow when pull-requests are merged
  # merging automatically closes the pull-request
  pull_request:
    types:
      - closed
  # workflow_dispatch allows the action to be run manually
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event_name }}
      - run: echo The github.head_ref is ${{ github.head_ref }}
      - run: echo The github.base_ref is ${{ github.base_ref }}
      - run: echo The github.ref is ${{ github.ref }}
      - run: echo The github.ref_name is ${{ github.ref_name }}
      - run: echo the github.sha is ${{ github.sha }}
      - uses: actions/checkout@v3
        # Ref needs to be explicit for pull-request trigger
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php

  commit-changes:
    needs: php-cs-fixer
    runs-on: ubuntu-latest

    steps:
      # See https://github.com/marketplace/actions/git-auto-commit
      # TODO: specify spcefic version
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Action Hero: PHP-CS-Fixer"
