name: auto-formatting action hero

on:
  push:
    branches:
      - master
      - devel
  # workflow_dispatch allows the action to be run manually
  workflow_dispatch:

jobs:
  autoformat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run PHP-CS-Fixer
        # See https://hub.docker.com/r/oskarstark/php-cs-fixer-ga
        uses: docker://oskarstark/php-cs-fixer-ga:3.7.0
        with:
          args: --config=.php-cs-fixer.php --diff

      - name: Install prettier
        run: |
          npm install --global prettier@2.6.2
          prettier --version

      - name: Run prettier
        # Uses config file .prettierrc
        run: prettier --write .

      - name: Install black
        run: |
          pip install black
          black --version

      - name: Run black
        run: black . -v

      # See https://github.com/marketplace/actions/git-auto-commit
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Autoformatted by Autoformatting Action Hero"
          commit_user_name: "Autoformatting Action Hero"
