name: PHP-CS-Fixer
on: [push]
jobs:
  Obtain-modified-files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    steps:
      - name: checkout branch with history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get changed files
        id: changes
        run: echo "::set-output name=changed::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }}..${{ github.event.after }} | xargs)"
  Print-files:
    runs-on: ubuntu-latest
    needs: Obtain-modified-files
    if: ${{ needs.Obtain-modified-files.outputs.changed }}
    steps:
      - name: echo changed files
        run: echo ${{ needs.Obtain-modified-files.outputs.changed }}
      - name: Install PHP-CS-Fixer
        run: |
          wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.0.1/php-cs-fixer.phar -O php-cs-fixer
          chmod a+x php-cs-fixer
          PHP_CS_FIXER_IGNORE_ENV=1
          ./php-cs-fixer --dry-run --diff fix ${{ needs.Obtain-modified-files.outputs.changed }}
