name: PHP-CS-Fixer
on: [push]
jobs:
  Obtain-modified-files:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    steps:
      - name: checkout branch with history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get changed files
        id: changes
        run: echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }}..${{ github.event.after }} | xargs)"
  Print-files:
    runs-on: ubuntu-latest
    needs: Obtain-modified-files
    if: ${{ needs.Obtain-modified-files.outputs.all }}
    steps:
      - name: echo changed files
        run: echo ${{ needs.Obtain-modified-files.outputs.all }}
      - name: echo modified files in this commit
        run: echo ${{ github.event.commits[modified] }}
      - name: echo added filed in this commit
        run: echo ${{ github.event.commits[added] }}
