name: auto-formatting action hero
on:
  push:
    branches:
      - master
      - devel
  pull_request:
    types:
      - closed
  # workflow_dispatch allows the action to be run manually
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP-CS-Fixer run
